FROM docker.io/golang:1.22.2-alpine3.18

MAINTAINER me@willsena.dev

WORKDIR /app

COPY ./graceful_shutdown go.mod /app

RUN go build -o /app/graceful-shutdown

EXPOSE 3000

CMD [ "/app/graceful-shutdown" ]